url: "https://eigenval.github.io"
baseurl: "/my-website"
permalink: /:categories/:year/:month/:day/:title/

title: My Website
description: A minimal Jekyll website hosted on GitHub Pages.
theme: minima



navbar:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"


    



