url: "https://eigenval.github.io"
baseurl: "/my-website"
permalink: /:categories/:year/:month/:day/:title/

title: Neuromath
description: A minimal Jekyll website hosted on GitHub Pages.
theme: minima



navbar:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "Research"
    url: "/research/"


plugins:
  - jekyll-tags

tags:
  layout: tag   # Specifies the layout template to use for tag pages
  permalink: /tags/:tag/   # Specifies the URL structure for tag pages
  
    

    



