title: My Website
description: A minimal Jekyll website hosted on GitHub Pages.
theme: minima
permalink: /:categories/:year/:month/:day/:title/


navbar:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"

remote_theme: "eigenval/my-website"
    



