url: "https://eigenval.github.io"
baseurl: "/my-website"


title: My Website
description: A minimal Jekyll website hosted on GitHub Pages.
theme: jekyll-theme-tactile
permalink: /:categories/:year/:month/:day/:title/


navbar:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"


    



